
export type Colormap =
    | "jet"
    | "hsv"
    | "hot"
    | "cool"
    | "spring"
    | "summer"
    | "autumn"
    | "winter"
    | "bone"
    | "copper"
    | "greys"
    | "YIGnBu"
    | "greens"
    | "YIOrRd"
    | "bluered"
    | "RdBu"
    | "picnic"
    | "rainbow"
    | "portland"
    | "blackbody"
    | "earth"
    | "electric"
    | "magma"
    | "viridis"
    | "inferno"
    | "plasma"
    | "turbo"
    | "cubehelix"
    | "alpha"
    | "bathymetry"
    | "cdom"
    | "chlorophyll"
    | "density"

export type PlayheadMode = "page" | "stop" | "loop" | "continue" | "scroll" | "scrub";

export type Backend = "webaudio" | "html5";